FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

COPY ./Domain/. .  app/Domain/ 
COPY ./Application/. .  app/Application/ 
COPY ./Infrastructure/. .  app/Infrastructure/ 
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["UserQueryApi", "UserQueryApi.dll"]